# Generated by Django 3.2.6 on 2021-10-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211003_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='photos/courses'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lectures', to='courses.courses'),
        ),
    ]
