# Generated by Django 3.2.6 on 2021-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211006_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_link',
            field=models.TextField(),
        ),
    ]
