# Generated by Django 3.2.6 on 2021-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_videos_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default='', upload_to='videos'),
            preserve_default=False,
        ),
    ]
