# Generated by Django 3.2.6 on 2021-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20211006_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='description',
            new_name='description_after',
        ),
        migrations.AddField(
            model_name='videos',
            name='description_before',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
