# Generated by Django 3.2.6 on 2021-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20211006_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
