# Generated by Django 3.2.6 on 2021-10-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_answers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='courses.questions'),
            preserve_default=False,
        ),
    ]
