# Generated by Django 3.2.6 on 2021-10-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20211006_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question_answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='courses.questions'),
            preserve_default=False,
        ),
    ]
