# Generated by Django 3.2.6 on 2021-10-07 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_childmodel_parentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='is_right',
        ),
        migrations.AddField(
            model_name='questions',
            name='right_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.answers'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_children', to='courses.parentmodel'),
        ),
    ]
