# Generated by Django 3.2.6 on 2021-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20211020_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='exams'),
        ),
    ]
