# Generated by Django 3.2.6 on 2021-10-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_exams_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='img',
        ),
        migrations.CreateModel(
            name='exam_solves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('right_answer', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exams')),
            ],
        ),
    ]
