# Generated by Django 3.2.6 on 2021-10-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_questions_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exams')),
            ],
        ),
    ]
