# Generated by Django 3.2.6 on 2021-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_exam_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_grades',
            name='total',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
