# Generated by Django 3.2.6 on 2021-10-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_exam_grades_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Final_exams',
        ),
    ]
