# Generated by Django 3.2.6 on 2021-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('volt', models.IntegerField()),
                ('ampere', models.IntegerField()),
                ('watt', models.IntegerField()),
                ('digram', models.ImageField(upload_to='photos')),
                ('pdf', models.FileField(upload_to=None)),
                ('sell_link', models.URLField()),
                ('how_to_pair', models.TextField()),
                ('is_rf', models.BooleanField()),
                ('video_link', models.URLField()),
                ('voice_command_options', models.TextField()),
                ('number_of_gangs', models.IntegerField()),
                ('load_per_gang', models.IntegerField()),
                ('total_load', models.IntegerField()),
                ('working_temp', models.IntegerField()),
                ('resistance_code', models.IntegerField()),
                ('material', models.TextField()),
                ('common_questions', models.TextField()),
            ],
        ),
    ]
