# Generated by Django 3.2.6 on 2021-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='voice_command_options',
            field=models.CharField(max_length=150),
        ),
    ]
