# Generated by Django 3.2.6 on 2021-10-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categories_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='common_questions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='how_to_pair',
        ),
    ]
