# Generated by Django 3.2.6 on 2021-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_how_to_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='products.Products'),
        ),
    ]
