# Generated by Django 3.2.6 on 2021-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_categories_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_433mhz_remote_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_lan_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_remote_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_share_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_single_count_down_timing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_smart_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_sync_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_rf',
            field=models.BooleanField(default=False),
        ),
    ]
