# Generated by Django 3.2.6 on 2021-10-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211008_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pdf1',
            new_name='pdf',
        ),
    ]
