# Generated by Django 3.2.6 on 2021-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_products_is_433mhz_remote_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pdf',
            new_name='quick_start',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pdf2',
            new_name='specification',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pdf3',
            new_name='user_manual',
        ),
        migrations.AlterField(
            model_name='products',
            name='load_per_gang',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_load',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='working_temp',
            field=models.CharField(max_length=150),
        ),
    ]
