# Generated by Django 3.2.6 on 2021-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20211008_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='resistance_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
