# Generated by Django 3.2.6 on 2021-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20211008_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='programing_video_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='programing_video_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
