# Generated by Django 3.2.6 on 2021-10-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_products_digram_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ampere',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='load_per_gang',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='number_of_gangs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_load',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='voice_command_options',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='volt',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='watt',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
