# Generated by Django 3.2.6 on 2021-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20211010_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='products',
            field=models.ManyToManyField(to='products.Products'),
        ),
    ]
