# Generated by Django 3.2.6 on 2021-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_is_remote_control_products_is_app_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='answer',
            new_name='ar_answer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='ar_question',
        ),
        migrations.AddField(
            model_name='products',
            name='ar_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='ar_how_to_pair',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tools',
            name='ar_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
