# Generated by Django 3.2.6 on 2021-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20211014_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ar_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ar_question',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
