# Generated by Django 3.2.6 on 2021-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20211014_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tools'),
        ),
    ]
