# Generated by Django 3.2.6 on 2021-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_products_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='digram',
            field=models.ImageField(upload_to='products/digram'),
        ),
        migrations.AlterField(
            model_name='products',
            name='digram_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/digram'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quick_start',
            field=models.FileField(blank=True, null=True, upload_to='products/quick_start'),
        ),
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.FileField(blank=True, null=True, upload_to='products/specification'),
        ),
        migrations.AlterField(
            model_name='products',
            name='user_manual',
            field=models.FileField(blank=True, null=True, upload_to='products/user_manual'),
        ),
    ]
