# Generated by Django 3.2.6 on 2021-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20211020_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tools',
            field=models.ManyToManyField(blank=True, to='products.Tools'),
        ),
    ]
